wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688116333.362143
    t:
      1:
      - 1
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.13
      5: 0.15.0
      6: 4.24.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: mse_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: mse_loss_epoch
      5: 1
      6:
      - 1
    - 1: Generated samples._type
      5: 1
      6:
      - 1
    - 1: Generated samples.sha256
      5: 1
      6:
      - 1
    - 1: Generated samples.size
      5: 1
      6:
      - 1
    - 1: Generated samples.path
      5: 1
      6:
      - 1
    - 1: Generated samples.format
      5: 1
      6:
      - 1
    - 1: Generated samples.width
      5: 1
      6:
      - 1
    - 1: Generated samples.height
      5: 1
      6:
      - 1
    - 1: Generated samples.caption
      5: 1
      6:
      - 1
in_channels:
  desc: null
  value: 2
out_channels:
  desc: null
  value: 2
image_size:
  desc: null
  value:
  - 128
  - 128
timesteps:
  desc: null
  value: 1000
lr:
  desc: null
  value: 4.5e-05
weight_decay:
  desc: null
  value: 1.0e-07
precision:
  desc: null
  value: 32
target_shape:
  desc: null
  value:
  - 64
  - 128
  - 128
n_samples:
  desc: null
  value: 500
modalities:
  desc: null
  value:
  - flair
  - seg
binarize:
  desc: null
  value: true
train_ratio:
  desc: null
  value: 1.0
npy_path:
  desc: null
  value: ./data/brats_preprocessed.npy
root_path:
  desc: null
  value: ../../common_data/RSNA_ASNR_MICCAI_BraTS2021_TrainingData_16July2021
batch_size:
  desc: null
  value: 16
shuffle:
  desc: null
  value: true
num_workers:
  desc: null
  value: 6
slice_idx:
  desc: null
  value: 32
