wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688116226.274914
    t:
      1:
      - 1
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 3
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.13
      5: 0.15.0
      6: 4.24.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
